name: Create Release

on: 
  push:
    tags:
    - '*'

jobs:
  createNotes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Previous Tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1
    - name: Get New Tag
      id: nexttag
      run: |
        NEW_TAG=${GITHUB_REF#refs/tags/}
        echo ${NEW_TAG}
        echo ::set-output name=tag::${NEW_TAG}
    - uses: actions/setup-node@v2
    - name: Generate Release Notes
      id: notes
      run: |
        NOTES=$(npx generate-github-release-notes jrjohnson test-release-workspace ${{ steps.previoustag.outputs.tag }} ${{steps.newtag.outputs.tag}})
        echo ${NOTES}
        echo ::set-output name=releaseNotes::${NOTES}
    - run: echo ${{steps.notes.content}}
    # - uses: ncipollo/release-action@v1
    #   with:
    #     body: ${{steps.notes.releaseNotes}}
    #     token: ${{ secrets.GITHUB_TOKEN }}