name: Create Release

on: 
  push:
    tags:
    - '*'

jobs:
  createNotes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get Previous Tag
      id: previousT
      run: |
        PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
        echo ${PREVIOUS_TAG}
        echo "::set-output name=tag::${PREVIOUS_TAG}
    - name: Get New Tag
      id: nextTag
      run: |
        git tag
        NEW_TAG=${GITHUB_REF#refs/tags/}
        echo ${NEW_TAG}
        echo ::set-output name=tag::${NEW_TAG}
    - uses: actions/setup-node@v2
    - name: Generate Release Notes
      id: notes
      run: |
        NOTES=$(npx generate-github-release-notes jrjohnson test-release-workspace ${{ steps.previousTag.outputs.tag }} ${{steps.nextTag.outputs.tag}})
        echo ${NOTES}
        echo ::set-output name=releaseNotes::${NOTES}
    - run: echo ${{steps.notes.content}}
    # - uses: ncipollo/release-action@v1
    #   with:
    #     body: ${{steps.notes.releaseNotes}}
    #     token: ${{ secrets.GITHUB_TOKEN }}