name: Create Release

on: 
  push:
    tags:
    - '*'

jobs:
  createNotes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Get Previous tag'
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
    - name: Get Tag
      id: nexttag
      run: |
        PREVIOUS_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
        echo ${PREVIOUS_TAG}
        echo ::set-output name=previous::${PREVIOUS_TAG}
    - uses: actions/setup-node@v2
    - name: Generate Release Notes
      id: notes
      run: |
        NOTES=$(npx generate-github-release-notes jrjohnson test-release-workspace ${{steps.tag.outputs.previous}} ${{steps.tag.outputs.new}})
        echo ${NOTES}
        echo ::set-output name=releaseNotes::${NOTES}
    - run: echo ${{steps.notes.content}}
    # - uses: ncipollo/release-action@v1
    #   with:
    #     body: ${{steps.notes.releaseNotes}}
    #     token: ${{ secrets.GITHUB_TOKEN }}